version: "3"

services:
  frontend:
    build: ./app
    container_name: frontend
    depends_on:
      - swag
    restart: unless-stopped
  swag:
    build: ./
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=10000
      - TZ=America/New_York
      - URL=edisonmt.com
      - SUBDOMAINS=www
      - VALIDATION=http
      - EMAIL=edisonpremise@gmail.com
    volumes:
      - ~/config:/config
    ports:
      - 443:443
      - 80:80
      - 1935:1935
    restart: unless-stopped
