version: "3"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - edisonmt.env
    ports:
      - 1935:1935
    restart: unless-stopped
  swag:
    image: linuxserver/letsencrypt
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=edisonmt.com
      - SUBDOMAINS=www,api,flv
      - VALIDATION=http
      - EMAIL=edisonpremise@gmail.com
    volumes:
      - ~/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
